from enum import Enum

class TokenType(Enum):
    ELSE = 'else'
    IF = 'if'
    INT = 'int'
    RETURN = 'return'
    VOID = 'void'
    WHILE = 'while'

    PLUS = '+'
    MINUS = '-'
    TIMES = '*'
    DIVIDE = '/'
    STHAN = '<'
    SETHAN = '<='
    BTHAN = '>'
    BETHAN = '>='
    COMPAREEQUALS = '=='
    NOTEQUALS = '!='
    EQUALS = '='
    SEMICOLON = ';'
    COMA = ','
    LPAREN = '('
    RPAREN = ')'
    LBRACKET = '['
    RBRACKET = ']'
    LKEY = '{'
    RKEY = '}'

    ID = 'id'
    NUM = 'num'
    COMMENT = 'comment'
    ERROR = 'error'
    ENDFILE = 'endfile'